DROP TABLE IF EXISTS car_rental;
CREATE TABLE car_rental
(
    id      INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    domain  VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    owner   VARCHAR(255) NOT NULL,
    logo    VARCHAR(255) NOT NULL
);